---
- name: Running show commands on Cisco IOS
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Running multiple commands
      ios_command:
        commands:
          - show ip int brief

      register: print_output

    - debug: var=print_output.stdout_lines
